# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20170426_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='DDnum',
            new_name='IDnum',
        ),
    ]
