# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20170426_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='名字')),
            ],
        ),
    ]
