# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20170429_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='', max_length=10, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
