# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20170505_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
    ]
