# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20170506_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
